### ISSUE TITLE
Module build failed: ReferenceError: [BABEL]

### ISSUE THREAD

**Issue by Thraithep** [prakhar1989/react-tags#140]
I import react-tag-input in my project.And my project can't build with webpack.

this's my package.config.I try to solve it.

  "devDependencies": {
    "awesome-bootstrap-checkbox": "^1.0.0-alpha.4",
    "babel-core": "^6.23.1",
    "babel-loader": "^6.3.2",
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-react": "^6.16.0",
    "babel-preset-stage-0": "^6.22.0",
    "babel-preset-stage-1": "^6.22.0",
    "css-loader": "^0.26.1",
    "file-loader": "^0.10.0",
    "fine-uploader-wrappers": "^0.1.1",
    "node-sass": "^4.3.0",
    "react-addons-css-transition-group": "^15.4.2",
    "react-bootstrap": "^0.30.7",
    "react-bootstrap-date-picker": "^4.0.0",
    "react-dom": "^15.4.2",
    "react-fine-uploader": "^0.5.0",
    "react-images": "^0.5.2",
    "react-modal": "^1.6.5",
    "react-notification-system": "^0.2.11",
    "react-tag-input": "^4.6.2",
    "sass-loader": "^4.1.1",
    "style-loader": "^0.13.1",
    "url-loader": "^0.5.7",
    "webpack": "^2.2.1"
  },
  "dependencies": {
    "jquery": "^3.1.1",
    "react": "^15.4.2"
  }

**Comment by prakhar1989** [comment]
What's the error that you're seeing with webpack?

**Comment by Thraithep** [comment]
this's error

ERROR in ./~/react-tag-input/~/react-dnd/~/disposables/modules/index.js
Module build failed: ReferenceError: [BABEL] Z:\dev\PharmaPack\PharmaPack.Admin\node_modules\react-tag-input\node_modules\react-dnd\node_modules\disposables\modules\index.js: Using removed Babel 5 option: Z:\dev\PharmaPack\PharmaPack.Admin\node_modules\react-tag-input\node_modules\react-dnd\node_modules\disposables\.babelrc.stage - Check out the corresponding stage-x presets http://babeljs.io/docs/plugins/#presets
    at Logger.error (Z:\dev\PharmaPack\PharmaPack.Admin\node_modules\babel-core\lib\transformation\file\logger.js:41:11)
    at OptionManager.mergeOptions (Z:\dev\PharmaPack\PharmaPack.Admin\node_modules\babel-core\lib\transformation\file\options\option-manager.js:216:20)
    at OptionManager.init (Z:\dev\PharmaPack\PharmaPack.Admin\node_modules\babel-core\lib\transformation\file\options\option-manager.js:374:12)
    at File.initOptions (Z:\dev\PharmaPack\PharmaPack.Admin\node_modules\babel-core\lib\transformation\file\index.js:216:65)
    at new File (Z:\dev\PharmaPack\PharmaPack.Admin\node_modules\babel-core\lib\transformation\file\index.js:139:24)
    at Pipeline.transform (Z:\dev\PharmaPack\PharmaPack.Admin\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (Z:\dev\PharmaPack\PharmaPack.Admin\node_modules\babel-loader\lib\index.js:38:20)
    at Object.module.exports (Z:\dev\PharmaPack\PharmaPack.Admin\node_modules\babel-loader\lib\index.js:133:12)
 @ ./~/react-tag-input/~/react-dnd/lib/decorateHandler.js 41:19-41

**Comment by prakhar1989** [comment]
This should be fixed now - updated the build and webpack configs. Feel free to re-open the issue if you still have problems.
